# LaTeX2HTML 97.1 (release) (July 13th, 1997)
# Associate images original text with physical files.


$key = q/{}epsfigfigure=vowels.eps{}FSF=1.6;AAT;/;
$cached_env_img{$key} = q|<IMG WIDTH="703" HEIGHT="259" ALIGN="BOTTOM" BORDER="0"
 SRC="img9.gif"
 ALT="\epsfig {figure=vowels.eps}
">|; 

$key = q/{}epsfigfigure=dais.eps{}FSF=1.6;AAT;/;
$cached_env_img{$key} = q|<IMG WIDTH="549" HEIGHT="393" ALIGN="BOTTOM" BORDER="0"
 SRC="img15.gif"
 ALT="\epsfig {figure=dais.eps}
">|; 

$key = q/{}epsfigfigure=frogschemas1.eps{}FSF=1.6;AAT;/;
$cached_env_img{$key} = q|<IMG WIDTH="563" HEIGHT="247" ALIGN="BOTTOM" BORDER="0"
 SRC="img12.gif"
 ALT="\epsfig {figure=frogschemas1.eps}
">|; 

$key = q/{}epsfigfigure=frogschemas2.eps{}FSF=1.6;AAT;/;
$cached_env_img{$key} = q|<IMG WIDTH="525" HEIGHT="246" ALIGN="BOTTOM" BORDER="0"
 SRC="img13.gif"
 ALT="\epsfig {figure=frogschemas2.eps}
">|; 

$key = q/{}epsfigfigure=minimax2.eps{}FSF=1.6;AAT;/;
$cached_env_img{$key} = q|<IMG WIDTH="641" HEIGHT="238" ALIGN="BOTTOM" BORDER="0"
 SRC="img1.gif"
 ALT="\epsfig {figure=minimax2.eps}
">|; 

$key = q/{_inline}eta{_inline}MSF=1.6;AAT;/;
$cached_env_img{$key} = q|<IMG WIDTH="34" HEIGHT="61" ALIGN="MIDDLE" BORDER="0"
 SRC="img20.gif"
 ALT="$\eta$">|; 

$key = q/{}epsfigfigure=hopfield.eps{}FSF=1.6;AAT;/;
$cached_env_img{$key} = q|<IMG WIDTH="601" HEIGHT="165" ALIGN="BOTTOM" BORDER="0"
 SRC="img8.gif"
 ALT="\epsfig {figure=hopfield.eps}
">|; 

$key = q/{_inline}p_ij(t)=frac[tau_ij(t)]^alphatimes[eta_ij(t)]^betasum_j=1^n[tau_ij(t)]^alphatimes[eta_ij(t)]^beta{_inline}MSF=1.6;AAT;/;
$cached_env_img{$key} = q|<IMG WIDTH="228" HEIGHT="77" ALIGN="MIDDLE" BORDER="0"
 SRC="img21.gif"
 ALT="$p_{ij}(t) =
\frac{[\tau_{ij}(t)]^{\alpha}\times[\eta_{ij}(t)]^{\beta}}{\sum_{j=1}^n[\tau_{ij}(t)]^{\alpha}\times[\eta_{ij}(t)]^{\beta}}$">|; 

$key = q/{}epsfigfigure=sl3.1.eps{}FSF=1.6;AAT;/;
$cached_env_img{$key} = q|<IMG WIDTH="334" HEIGHT="540" ALIGN="BOTTOM" BORDER="0"
 SRC="img2.gif"
 ALT="\epsfig {figure=sl3.1.eps}
">|; 

$key = q/{}epsfigfigure=sl3.2.eps{}FSF=1.6;AAT;/;
$cached_env_img{$key} = q|<IMG WIDTH="300" HEIGHT="540" ALIGN="BOTTOM" BORDER="0"
 SRC="img3.gif"
 ALT="\epsfig {figure=sl3.2.eps}
">|; 

$key = q/{}epsfigfigure=bbo.eps{}FSF=1.6;AAT;/;
$cached_env_img{$key} = q|<IMG WIDTH="549" HEIGHT="513" ALIGN="BOTTOM" BORDER="0"
 SRC="img10.gif"
 ALT="\epsfig {figure=bbo.eps}
">|; 

$key = q/{_inline}alpha,beta,rho{_inline}MSF=1.6;AAT;/;
$cached_env_img{$key} = q|<IMG WIDTH="70" HEIGHT="63" ALIGN="MIDDLE" BORDER="0"
 SRC="img23.gif"
 ALT="$\alpha, \beta, \rho$">|; 

$key = q/{}epsfigfigure=sl3.3.eps{}FSF=1.6;AAT;/;
$cached_env_img{$key} = q|<IMG WIDTH="392" HEIGHT="540" ALIGN="BOTTOM" BORDER="0"
 SRC="img4.gif"
 ALT="\epsfig {figure=sl3.3.eps}
">|; 

$key = q/{}epsfigfigure=perceptron1.eps{}FSF=1.6;AAT;/;
$cached_env_img{$key} = q|<IMG WIDTH="636" HEIGHT="288" ALIGN="BOTTOM" BORDER="0"
 SRC="img6.gif"
 ALT="\epsfig {figure=perceptron1.eps}
">|; 

$key = q/{}epsfigfigure=perceptron2.eps{}FSF=1.6;AAT;/;
$cached_env_img{$key} = q|<IMG WIDTH="598" HEIGHT="323" ALIGN="BOTTOM" BORDER="0"
 SRC="img7.gif"
 ALT="\epsfig {figure=perceptron2.eps}
">|; 

$key = q/{}epsfigfigure=ants.eps{}FSF=1.6;AAT;/;
$cached_env_img{$key} = q|<IMG WIDTH="634" HEIGHT="195" ALIGN="BOTTOM" BORDER="0"
 SRC="img18.gif"
 ALT="\epsfig {figure=ants.eps}
">|; 

$key = q/{_inline}rho{_inline}MSF=1.6;AAT;/;
$cached_env_img{$key} = q|<IMG WIDTH="34" HEIGHT="61" ALIGN="MIDDLE" BORDER="0"
 SRC="img19.gif"
 ALT="$\rho$">|; 

$key = q/{_inline}rightarrow{_inline}MSF=1.6;AAT;/;
$cached_env_img{$key} = q|<IMG WIDTH="42" HEIGHT="50" ALIGN="BOTTOM" BORDER="0"
 SRC="img5.gif"
 ALT="$\rightarrow$">|; 

$key = q/{_inline}m(H,t+1)=m(H,t)fracf(H)overlinef{_inline}MSF=1.6;AAT;/;
$cached_env_img{$key} = q|<IMG WIDTH="213" HEIGHT="72" ALIGN="MIDDLE" BORDER="0"
 SRC="img16.gif"
 ALT="$m(H,t+1)=m(H,t)\frac{f(H)}{\overline f}$">|; 

$key = q/{_inline}overlinef{_inline}MSF=1.6;AAT;/;
$cached_env_img{$key} = q|<IMG WIDTH="36" HEIGHT="69" ALIGN="MIDDLE" BORDER="0"
 SRC="img17.gif"
 ALT="$\overline f$">|; 

$key = q/{}epsfigfigure=jump.eps{}FSF=1.6;AAT;/;
$cached_env_img{$key} = q|<IMG WIDTH="526" HEIGHT="333" ALIGN="BOTTOM" BORDER="0"
 SRC="img14.gif"
 ALT="\epsfig {figure=jump.eps}
">|; 

$key = q/{_inline}alpha,beta{_inline}MSF=1.6;AAT;/;
$cached_env_img{$key} = q|<IMG WIDTH="54" HEIGHT="63" ALIGN="MIDDLE" BORDER="0"
 SRC="img22.gif"
 ALT="$\alpha, \beta$">|; 

$key = q/{}epsfigfigure=neurontiming.eps{}FSF=1.6;AAT;/;
$cached_env_img{$key} = q|<IMG WIDTH="549" HEIGHT="594" ALIGN="BOTTOM" BORDER="0"
 SRC="img11.gif"
 ALT="\epsfig {figure=neurontiming.eps}
">|; 

1;

