/*
 * SixStackWin.java
 *
 * Created on 18 December 2000, 21:34
 */

package Solitaire;

/**
 *
 * @author  Ian Wallis
 * @version 
 */
public class SixStackWin extends javax.swing.JApplet {

    /** Creates new form SixStackWin */
    public SixStackWin() {
        initComponents ();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents () {//GEN-BEGIN:initComponents

    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
